global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8001']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8002']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8003']

  - job_name: 'recommendation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recommendation-service:8004']

  - job_name: 'seckill-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['seckill-service:8005']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
