{
 "title": "Microservices Overview",
 "tags": [
  "ecommerce",
  "spring-boot",
  "actuator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(up, job)" }
  ]
 },
 "panels": [
  {
   "title": "Service Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP RPS by Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"$job\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Rate by Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"$job\",status=~\"5..\"}[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Avg Latency by Job (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{job=~\"$job\"}[5m])) by (job) / sum(rate(http_server_requests_seconds_count{job=~\"$job\"}[5m])) by (job)) * 1000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Heap Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\",area=\"heap\"}) by (job) / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Threads Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}